version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "exercicio-04"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x0sm4hei2ieg"
s3_prefix = "exercicio-04"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
