version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "exercicio-05"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x0sm4hei2ieg"
s3_prefix = "exercicio-05"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Domain=\"bitly.com\" HostedZoneId=\"XJGYF3453769GVHJGI6\" CertificateArn=\"arn:aws:acm:us-east-1:{AccountId}:certificate/{Id}\""
