AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Template básico para você resolver seus exercícios

Resources: 
  dmaClientes: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "N"
        -
          AttributeName: "cidade"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
      TableName: "dma-clientes"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "cidade-index"
          KeySchema:
            - 
              AttributeName: "cidade"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"

  helloworld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./02/src
      Description: A starter AWS Lambda function.
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /exercise-02/{id}
            Method: get
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref dmaClientes
