AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Description: Template dojo dupla Romulo e Henrique

Resources:
  ExercisesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for the Serverless Api
          Quota:
            Limit: 50
            Period: MONTH
          Tags:
            - Key: Name
              Value: Exercise01ApiUsagePlan

  Exercise01Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Exercise-01-function
      CodeUri: ./01
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Exercise01Api:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-01
            Method: GET
            Auth:
              ApiKeyRequired: true

  Exercise02ClientFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Exercise-02-client-function
      CodeUri: ./02
      Handler: app.get
      Runtime: nodejs12.x
      Policies:
        -
          DynamoDBReadPolicy:
            TableName: !Ref Exercise02Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Exercise02Table
      Events:
        Exercise01Api:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-02/{id}
            Method: GET
            Auth:
              ApiKeyRequired: true

  Exercise02CidadeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Exercise-02-cidade-function
      CodeUri: ./02
      Handler: app.query
      Runtime: nodejs12.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Exercise02Table
      Events:
        Exercise02Api:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-01/cidade/{cidade}
            Method: GET
            Auth:
              ApiKeyRequired: true

  Exercise02Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "cidade"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
      TableName: !Sub "${AWS::StackName}-clientes"
      GlobalSecondaryIndexes:
        - 
          IndexName: "cidade-index"
          KeySchema:
            -
              AttributeName: "cidade"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"

Outputs:
  Exercise01Function:
    Value: !Ref Exercise01Function
  Exercise02ClientFunction:
    Value: !Ref Exercise02ClientFunction
  Exercise02CidadeFunction:
    Value: !Ref Exercise02CidadeFunction
  Exercise02Table:
    Value: !Ref Exercise02Table
