AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Template básico para você resolver seus exercícios

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          UsagePlanName: marcosoares
          CreateUsagePlan: PER_API
          Quota:
            Limit: 500
            Period: MONTH
          Throttle:
            BurstLimit: 100
            RateLimit: 50

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Exercise-01-function-marcosoares
      CodeUri: ./01
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        ApiKey:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /exercise-01
            Method: GET
            Auth:
              ApiKeyRequired: true

Outputs:
  MyApiID:
    Description: ID da nossa API
    Value: !Ref MyApi