AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Template básico para você resolver seus exercícios

Resources:
  RecursoInutil: # TODO: remover para começar os exercícios
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-s3-de-exemplo

Outputs:
  RecursoInutil:
    Description: Saída criada de exemplo
    Value: !Ref RecursoInutils