AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Resolução dos exercícios

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30

Mappings:
  APIG:
    Stage:
      default: dojo

Resources:
  ExercisesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap [APIG, Stage, default]
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          UsagePlanName: !Sub '${AWS::StackName}-apiKey'
          CreateUsagePlan: PER_API
          Description: Usage plan for the Serverless Api
          Quota:
            Limit: 500
            Period: MONTH

  Exercise01Function:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Exercise01Api:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-01
            Method: GET
            Auth:
              ApiKeyRequired: true
      CodeUri: ./01
      Handler: Exercise-01-function.handler

  Exercise02DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "cidade"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
      TableName: !Sub "${AWS::StackName}-clientes"
      GlobalSecondaryIndexes:
        - IndexName: "cidade-index"
          KeySchema:
            - AttributeName: "cidade"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"

  Exercise02Function:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Exercise02DynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref Exercise02DynamoDBTable
      CodeUri: ./02
      Handler: Exercise-02-function.get
      Events:
        Exercise02ApiId:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-02/{id}
            Method: GET
            Auth:
              ApiKeyRequired: true

  Exercise02CidadeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Exercise02DynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref Exercise02DynamoDBTable
      CodeUri: ./02
      Handler: Exercise-02-function.query
      Events:
        Exercise02ApiCidade:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-02/cidade/{cidade}
            Method: GET
            Auth:
              ApiKeyRequired: true

  Exercise03DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-produtos

  Exercise03S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${AWS::StackName}-produtos

  Exercise03Function:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref Exercise03S3Bucket
        - DynamoDBWritePolicy:
            TableName:  !Ref Exercise03DynamoDBTable
      Environment:
        Variables:
          BUCKET_PRODUTOS: !Ref Exercise03S3Bucket
          TABLE_NAME: !Ref Exercise03DynamoDBTable
      Runtime: nodejs12.x
      CodeUri: ./03
      Handler: Exercise-03-function.handler
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)

Outputs:
  ExercisesApi:
    Value: !Join
      - '/'
      - - !Sub 'https://${ExercisesApi}.execute-api.${AWS::Region}.amazonaws.com'
        - !FindInMap [APIG, Stage, default]
  Exercise01Function:
    Value: !GetAtt Exercise01Function.Arn
  Exercise02DynamoDBTable:
    Value: !Ref Exercise02DynamoDBTable
  Exercise02Function:
    Value: !GetAtt Exercise02Function.Arn
  Exercise02CidadeFunction:
    Value: !GetAtt Exercise02CidadeFunction.Arn
  LambdaArn:
    Value: !GetAtt Exercise03Function.Arn
  TableName:
    Value: !Ref Exercise03DynamoDBTable
  BucketName:
    Value: !Ref Exercise03S3Bucket