AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Description: Template básico para você resolver seus exercícios

Resources:
  ExercisesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan para API Mando Rafael e Neviton
          Quota:
            Limit: 5000
            Period: MONTH
          Tags:
            - Key: Name
              Value: Exercise01ApiUsagePlan
      Models:
        Cliente:
          type: object
          required:
            - id
            - nome
            - documento
            - cidade
            - estado
            - pais
            - id_plano
          properties:
            id:
              type: integer
            nome:
              type: string
            documento:
              type: string
            cidade:
              type: string
            estado:
              type: string
            pais:
              type: string
            id_plano:
              type: integer
      GatewayResponses:
        DEFAULT_4XX:
          StatusCode: 400
          ResponseTemplates: 
            "application/json": '{"message": "Invalid Input"}'

  Exercise01Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Events:
        Exercise01Api:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-01
            Method: GET
            Auth:
              ApiKeyRequired: true
      CodeUri: ./01
      Handler: Exercise-01-function.handler

  Exercise02Function:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Exercise02DynamoDBTable
      Runtime: nodejs12.x
      Events:
        Exercise02ApiId:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-02/{id}
            Method: GET
            Auth:
              ApiKeyRequired: true
        Exercise02ApiCidade:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-02/cidade/{cidade}
            Method: GET
            Auth:
              ApiKeyRequired: true
      CodeUri: ./02
      Handler: Exercise-02-function.handler

  Exercise02DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "N"
        - 
          AttributeName: "cidade"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"     
      ProvisionedThroughput: 
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
      TableName: !Sub ${AWS::StackName}-mrn-clientes
      GlobalSecondaryIndexes: 
        - 
          IndexName: "cidade-index"
          KeySchema: 
            - 
              AttributeName: "cidade"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "3"
            WriteCapacityUnits: "3"

  Exercise03DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
          
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
  
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-produtos
  
  Exercise03S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${AWS::StackName}-produtos

  Exercise03Function:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref Exercise03S3Bucket
        - DynamoDBWritePolicy:
            TableName:  !Ref Exercise03DynamoDBTable
      Environment:
        Variables:
          BUCKET_PRODUTOS: !Ref Exercise03S3Bucket
          TABELA_PRODUTOS: !Ref Exercise03DynamoDBTable
      Runtime: nodejs12.x
      CodeUri: ./03
      Handler: Exercise-03-function.handler
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)

  Exercise04ProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - SQSSendMessagePolicy: 
            QueueName: !GetAtt Exercise04SQSQueue.QueueName
      Environment:
        Variables:
          QUEUE_URL: !Ref Exercise04SQSQueue
      Runtime: nodejs12.x
      Events:
        Exercise04ApiId:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-04/
            Method: POST
            Auth:
              ApiKeyRequired: true
            RequestModel:
              Model: Cliente
              Required: true
              ValidateBody: true
      CodeUri: ./04
      Handler: Exercise-04-Producer-function.handler

  Exercise04SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-Queue
      DelaySeconds: 60

  Exercise04ConsumerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./04
      Handler: Exercise-04-Consumer-function.handler
      Runtime: nodejs12.x
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "dynamodb:BatchWriteItem"
            Resource:
              - !GetAtt Exercise02DynamoDBTable.Arn
      Environment:
        Variables:
          CLIENTES_TABLE: !Ref Exercise02DynamoDBTable
          TABELA_MRN_CLIENTES: !Ref Exercise02DynamoDBTable          
      Events:
        ConsumerQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt Exercise04SQSQueue.Arn
            BatchSize: 3

  Exercise05AliasesDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-aliases
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "tipo"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "tipo-index"
          KeySchema: 
            - 
              AttributeName: "tipo"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          

  BitlyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-userPool'
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UsernameConfiguration:
        CaseSensitive: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 1
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: 'family_name'
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: 'birthdate'
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true

  BitlyFreeUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: free_account
      Precedence: 1
      UserPoolId: !Ref BitlyUserPool

  BitlyPremiumUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: premium_account
      Precedence: 2
      UserPoolId: !Ref BitlyUserPool

  BitlyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-userPoolClient'
      GenerateSecret: false
      UserPoolId: !Ref BitlyUserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs: [http://localhost:3000]
      AllowedOAuthFlows: [implicit, code]
      AllowedOAuthScopes: [email, openid]
      SupportedIdentityProviders: [COGNITO]

  BitlyUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref BitlyUserPool
      Domain: !Ref AWS::StackName

  BitlyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt BitlyUserPool.Arn
  
  BitlyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref BitlyApi
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}


Outputs:
  Exercise01Function:
    Description: Saída Exercicio 01
    Value: !Ref Exercise01Function

  BucketName:
    Description: Bucket para produtos.csv
    Value: !Ref Exercise03S3Bucket
  
  LambdaArn:
    Description: Lambda Function ARN
    Value: !GetAtt Exercise03Function.Arn
  
  TableName:
    Description: Products table name
    Value: !Ref Exercise03DynamoDBTable

  BitlyAuthURL:
    Value: !Sub 'https://${BitlyUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${BitlyUserPoolClient}&response_type=token&redirect_uri=http://localhost:3000'

