AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Template básico para você resolver seus exercícios

Resources:

  ExercisesApi:
    Type: AWS::Serverless::Api  
    Properties:    
      StageName: Prod
      Auth:
        ApiKeyRequired: true

  Exercise01Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Events:
        Exercise01Api:
          Type: Api
          Properties:
            RestApiId: !Ref ExercisesApi
            Path: /exercise-01
            Method: GET
            Auth:
              ApiKeyRequired: true
      CodeUri: ./01
      Handler: Exercise-01-function.handler

Outputs:
  Exercise01Function:
    Description: Saída Exercicio 01
    Value: !Ref Exercise01Function