version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patrick--hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x0sm4hei2ieg"
s3_prefix = "patrick--hello-world"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
